# Generated by Django 4.2.10 on 2026-07-04 13:31

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hitcount.models
import pgvector.django.vector
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hitcount", "0004_auto_20200704_0933"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1500)),
                ('ingredients', tinymce.models.HTMLField(blank=True, null=True)),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
                ('date_post', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('timing', models.IntegerField(blank=True, default=0)),
                ('servings', models.IntegerField(default=0)),
                ('type', models.CharField(default='type', max_length=100)),
                ('cuisine', models.CharField(default='cuisine', max_length=100)),
                ('category', models.CharField(default='category', max_length=100)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('difficulty', models.CharField(default='difficulty', max_length=100)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(default='avatar.jpg', upload_to='profile')),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20, null=True)),
                ('bio', models.TextField(default='Bio')),
                ('send_email', models.BooleanField(default=True)),
                ('credits', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('earned_credits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('redeemed_credits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('credits_spent', models.PositiveIntegerField(default=0)),
                ('facebook', models.URLField(blank=True, max_length=400, validators=[django.core.validators.URLValidator()])),
                ('instagram', models.URLField(blank=True, max_length=400, validators=[django.core.validators.URLValidator()])),
                ('twitter', models.URLField(blank=True, max_length=400, validators=[django.core.validators.URLValidator()])),
                ('threads', models.URLField(blank=True, max_length=400, validators=[django.core.validators.URLValidator()])),
                ('youtube', models.URLField(blank=True, max_length=400, validators=[django.core.validators.URLValidator()])),
                ('website', models.URLField(blank=True, max_length=400, validators=[django.core.validators.URLValidator()])),
                ('preference_type', models.CharField(choices=[('Select', 'Select'), ('Breakfast recipes', 'Breakfast recipes'), ('Lunch recipes', 'Lunch recipes'), ('Evening Snack recipes', 'Evening Snack recipes'), ('Dinner recipes', 'Dinner recipes')], default='Select', max_length=100)),
                ('preference_category', models.CharField(choices=[('Select', 'Select'), ('Veg recipes', 'Veg recipes'), ('Non-Veg recipes', 'Non-Veg recipes')], default='Select', max_length=100)),
                ('preference_cuisine', models.CharField(choices=[('Select', 'Select'), ('Indian cuisine', 'Indian cuisine'), ('American cuisine', 'American cuisine'), ('Italian cuisine', 'Italian cuisine')], default='Select', max_length=100)),
                ('hit_count', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hitcount.hitcount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTasteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste_vector', pgvector.django.vector.VectorField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(blank=True, default='#DBCBBD', max_length=20, null=True)),
                ('secondary_color', models.CharField(blank=True, default='#F0ECE3', max_length=20, null=True)),
                ('tertiary_color', models.CharField(blank=True, default='#221e20', max_length=20, null=True)),
                ('active_link_color', models.CharField(blank=True, default='#9F8772', max_length=20, null=True)),
                ('hover_color', models.CharField(blank=True, default='#9C938B', max_length=20, null=True)),
                ('theme', models.CharField(default='day', max_length=20)),
                ('neutral_primary', models.CharField(blank=True, default='#DBCBBD', max_length=20, null=True)),
                ('neutral_secondary', models.CharField(blank=True, default='#D8D9DA', max_length=20, null=True)),
                ('schedule_enabled', models.BooleanField(default=False)),
                ('schedule_mode', models.CharField(default='auto', max_length=10)),
                ('night_start', models.TimeField(blank=True, null=True)),
                ('night_end', models.TimeField(blank=True, null=True)),
                ('theme_name', models.CharField(blank=True, default='', max_length=100)),
                ('use_colors_from_image', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='Location', max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RedeemedCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('redeemed_timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeRecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('clicked', models.BooleanField(default=False)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummyrecipes.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes', to='yummyrecipes.profile'),
        ),
        migrations.AddField(
            model_name='post',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='yummyrecipes.profile'),
        ),
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummyrecipes.post')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummyrecipes.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditSpentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('spent_timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummyrecipes.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('earned_timestamp', models.DateTimeField(auto_now_add=True)),
                ('credit_action', models.CharField(choices=[('earned', 'Earned'), ('redeemed', 'Redeemed'), ('new_recipe', 'New recipe'), ('deleted', 'Deleted')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_comment', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_update_comment', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.TextField()),
                ('comment_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_super', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummyrecipes.post')),
            ],
        ),
        migrations.CreateModel(
            name='BlogHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummyrecipes.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_histories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YearlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026)),
                ('goal', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_goals', to='yummyrecipes.profile')),
            ],
            options={
                'unique_together': {('profile', 'year')},
            },
        ),
        migrations.CreateModel(
            name='searchedRecipesRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_searched', models.DateTimeField(default=datetime.datetime.now)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_rankings', to='yummyrecipes.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_search_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('recipe', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('follower', 'following')},
            },
        ),
    ]
