from django.urls import path

from .utils.helper_utils import email_template, export_user_data, save_location
from .utils.home_utils import add_to_favorites
from .utils.notification_utils import clear_all_notifications, remove_notification
from .utils.pdf_utils import customer_render_pdf_view, shopping_list_pdf
from .utils.recipes_helper import translate_content
from .utils.summarizer import summarize_content
from .views.accounts import UpdatePassword, UpdateProfile, acc_settings, profile_details_partial, profile_view
from .views.appearance import (
    appearance,
    apply_ai_theme,
    apply_day_theme,
    apply_night_theme,
    custom_theme,
    generate_ai_theme,
    save_schedule,
)
from .views.authentications import delete_account, guest_mode, login_view, logout_view, signup_view, topostlogin
from .views.credits_management import (
    credits,
    dashboard_credit_earned,
    dashboard_credit_monthly,
    dashboard_credit_redeemed,
    dashboard_credit_spent,
    dashboard_credits,
    dashboard_redeem_credit,
    delete_credit_history,
    delete_redeemed_history,
    delete_spent_history,
)
from .views.custom_passwords import (
    CustomLoginView,
    CustomPasswordResetCompleteView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetDoneView,
    CustomPasswordResetView,
    CustomSocialSignupView,
)
from .views.home_views import HomeView, landingpg
from .views.kitchen_ai import generate_recipe_content, generate_recipe_with_ai_image
from .views.recipes_comparison import compare_recipes, compare_recipes_new, compare_view
from .views.recipes_display import (
    cuisines,
    explore_filter,
    exploreRecipesView,
    load_more_trending_recipes,
    meal_detail,
    postDetailView,
    refresh_recipes,
    trendingRecipesView,
)
from .views.recipes_history import blog_history, bulk_delete_blogs, delete_all_blog_history, delete_entry
from .views.recipes_management import Updaterecipeview, dashboard_delete_recipe, dislike_view, like_view, post_post_view
from .views.search import searchresults, userchannel
from .views.user_activity import (
    dashboard_all_views,
    dashboard_disliked_recipes,
    dashboard_dislikes,
    dashboard_dislikes_received,
    dashboard_favourites,
    dashboard_liked_recipes,
    dashboard_likes,
    dashboard_likes_received,
    dashboard_network,
    dashboard_network_followers,
    dashboard_network_following,
    dashboard_top_disliked_recipes,
    dashboard_top_liked_recipes,
    dashboard_top_viewed,
    dashboard_views,
    dashboard_views_overview,
    feedback_view,
    follow_unfollow_user,
)
from .views.user_analytics import (
    dashboard,
    dashboard_my_recipes,
    dashboard_overview,
    dashboard_publishing_history,
    dashboard_recent_uploads,
    dashboard_recipe_cards,
    dashboard_recipe_list,
    dashboard_timeline,
    dashboard_timeline_overview,
    year_recap,
)

urlpatterns = [
    path("", landingpg, name="landingpg"),
    path("appearance/day/", apply_day_theme, name="apply_day_theme"),
    path("appearance/night/", apply_night_theme, name="apply_night_theme"),
    path("appearance/schedule/", save_schedule, name="save_schedule"),
    path("appearance/custom-theme/", custom_theme, name="custom_theme"),
    path("appearance/generate-ai-theme/", generate_ai_theme, name="generate_ai_theme"),
    path("appearance/apply-ai-theme/", apply_ai_theme, name="apply_ai_theme"),
    path("password_reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", CustomPasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("reset/done/", CustomPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("explore/", exploreRecipesView.as_view(), name="explore"),
    path("explore/filter/", explore_filter, name="explore_filter"),
    path("home/", HomeView.as_view(), name="home"),
    path("refresh-recipes/", refresh_recipes, name="refresh_recipes"),
    path("login/", login_view, name="login"),
    path("accounts/3rdparty/signup/", CustomSocialSignupView.as_view(), name="socialaccount_signup"),
    path("accounts/login/", CustomLoginView.as_view(), name="account_login"),
    path("login_required/<pk>/", topostlogin, name="topostlogin"),
    path("signup/", signup_view, name="signup"),
    path("logout/", logout_view, name="logout"),
    path("profile/", profile_view, name="profile"),
    path("profile/details/", profile_details_partial, name="profile_details_partial"),
    path("create-recipe/", post_post_view, name="createpost"),
    path("searchresults/", searchresults, name="searchresults"),
    path("recipe/<pk>/", postDetailView.as_view(), name="viewpost"),
    path("post/comment", postDetailView.as_view(), name="comment"),
    path("translate-content/", translate_content, name="translate_content"),
    path("like-view/", like_view, name="like-view"),
    path("dislike/", dislike_view, name="dislike-view"),
    path("user_channel/<first> <last>/<pk>/", userchannel, name="userchannelpage"),
    path("user_channel/<first>/<pk>/", userchannel, name="userchannelpage"),
    path("dashboard/", dashboard, name="dashboard"),
    path("dashboard/overview/", dashboard_overview, name="dashboard_overview"),
    path("dashboard/my-recipes/", dashboard_my_recipes, name="dashboard_my_recipes"),
    path("dashboard/recipe_list/", dashboard_recipe_list, name="dashboard_recipe_list"),
    path("dashboard/recipes/page/", dashboard_recipe_cards, name="dashboard_recipe_cards"),
    path("dashboard/delete/<int:pk>/", dashboard_delete_recipe, name="dashboard_delete_recipe"),
    path("editrecipe/<title>/<pk>/", Updaterecipeview, name="updaterecipe"),
    path("updateprofile/", UpdateProfile, name="updateprofile"),
    path("updatepassword/", UpdatePassword, name="updatepassword"),
    path("account_settings/", acc_settings, name="account_settings"),
    path("dashboard/likes/", dashboard_likes, name="dashboard_likes"),
    path("dashboard/likes/liked/", dashboard_liked_recipes, name="dashboard_liked_recipes"),
    path("dashboard/likes/received/", dashboard_likes_received, name="dashboard_likes_received"),
    path("dashboard/likes/top/", dashboard_top_liked_recipes, name="dashboard_top_liked_recipes"),
    path("dashboard/dislikes/", dashboard_dislikes, name="dashboard_dislikes"),
    path("dashboard/dislikes/disliked/", dashboard_disliked_recipes, name="dashboard_disliked_recipes"),
    path("dashboard/dislikes/received/", dashboard_dislikes_received, name="dashboard_dislikes_received"),
    path("dashboard/dislikes/top/", dashboard_top_disliked_recipes, name="dashboard_top_disliked_recipes"),
    path("<feed>/<pk>/download pdf/", customer_render_pdf_view, name="customerrender"),
    path("trending/", trendingRecipesView.as_view(), name="trending"),
    path("trending/load-more/", load_more_trending_recipes, name="more_trending_recipe"),
    path("dashboard/timeline/", dashboard_timeline, name="dashboard_timeline"),
    path("dashboard/timeline/overview/", dashboard_timeline_overview, name="dashboard_timeline_overview"),
    path("dashboard/timeline/monthly-activity/", dashboard_publishing_history, name="dashboard_publishing_history"),
    path("dashboard/timeline/recent-uploads/", dashboard_recent_uploads, name="dashboard_recent_uploads"),
    path("history/", blog_history, name="blog_history"),
    path("delete_entry/<pk>/", delete_entry, name="delete_blog"),
    path("delete_entry/", bulk_delete_blogs, name="bulk_delete"),
    path("delete-all/", delete_all_blog_history, name="delete_all_blog_history"),
    path("delete_account/", delete_account, name="delete_account"),
    path("recap/", year_recap, name="year_recap"),
    path("appearance/", appearance, name="appearance"),
    path("save_location/", save_location, name="save_location"),
    path("fav/<int:id>/", add_to_favorites, name="add_to_favorites"),
    path("dashboard/favourites/", dashboard_favourites, name="dashboard_favourites"),
    path("credits/", credits, name="credits"),
    path("dashboard/credits/", dashboard_credits, name="dashboard_credits"),
    path("dashboard/credits/history/monthly/", dashboard_credit_monthly, name="dashboard_credit_monthly"),
    path("dashboard/credits/redeem/", dashboard_redeem_credit, name="dashboard_redeem_credit"),
    path("dashboard/credits/history/earned/", dashboard_credit_earned, name="dashboard_credit_earned"),
    path("dashboard/credits/history/redeemed/", dashboard_credit_redeemed, name="dashboard_credit_redeemed"),
    path("dashboard/credits/history/spent/", dashboard_credit_spent, name="dashboard_credit_spent"),
    path("cuisines/<slug>/", cuisines, name="cuisines"),
    path("meal/<slug>/", meal_detail, name="meal_detail"),
    path("summarize/", summarize_content, name="summarize_content"),
    path("kitchenai/", generate_recipe_with_ai_image, name="kitchen_ai"),
    path("kitchenai/", generate_recipe_content, name="generaterecipe"),
    path("email_template/", email_template, name="email_template"),
    path("remove_notification/", remove_notification, name="remove_notification"),
    path("clear_all_notifications/", clear_all_notifications, name="clear_all_notifications"),
    path("dashboard/views/", dashboard_views, name="dashboard_views"),
    path("dashboard/views/overview/", dashboard_views_overview, name="dashboard_views_overview"),
    path("dashboard/views/top-viewed/", dashboard_top_viewed, name="dashboard_top_viewed"),
    path("dashboard/views/all/", dashboard_all_views, name="dashboard_all_views"),
    path("comparing/<pk>/", compare_recipes, name="compare_recipes"),
    path("comparing/", compare_recipes_new, name="compare_recipes"),
    path("comparing/<recipe_id1>/with/<recipe_id2>/", compare_view, name="compare_view"),
    path("feedback/", feedback_view, name="feedback"),
    path("profile/<str:username>/follow_unfollow/", follow_unfollow_user, name="follow_unfollow_user"),
    path("dashboard/network/", dashboard_network, name="dashboard_network"),
    path("dashboard/network/<int:year>/followers/", dashboard_network_followers, name="dashboard_network_followers"),
    path("dashboard/network/<int:year>/following/", dashboard_network_following, name="dashboard_network_following"),
    path("generate-audio/<int:pk>/", postDetailView.as_view(), name="generate_audio_file"),
    path("delete_credit_history/", delete_credit_history, name="delete_credit_history"),
    path("delete_redeemed_history/", delete_redeemed_history, name="delete_redeemed_history"),
    path("delete_spent_history/", delete_spent_history, name="delete_spent_history"),
    path("<title>/<pk>/shopping list/", shopping_list_pdf, name="shopping_list"),
    path("export-data/", export_user_data, name="export_data"),
    path("guest-mode/", guest_mode, name="guest_mode"),
]
