# Generated by Django 4.0.4 on 2022-04-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[('M', 'male'), ('F', 'female'), ('Other', 'not specified')]),
        ),
    ]
