# Generated by Django 4.0.4 on 2022-04-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0003_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Not to say', 'not specified')], max_length=20),
        ),
    ]
