# Generated by Django 4.0.4 on 2022-04-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0005_post_ingredients_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
