# Generated by Django 4.0.4 on 2022-04-27 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0006_alter_post_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
