# Generated by Django 4.0.4 on 2022-04-29 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0009_post_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='servings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='timing',
            field=models.IntegerField(default=0),
        ),
    ]
