# Generated by Django 4.0.4 on 2022-04-29 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0010_post_servings_alter_post_timing'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='types',
            field=models.CharField(default='choose', max_length=100),
        ),
    ]
