# Generated by Django 4.0.4 on 2022-04-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0012_rename_types_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like_count',
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
