# Generated by Django 4.0.4 on 2022-04-30 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0013_remove_post_like_count_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cuisine',
            field=models.CharField(default='cuisine', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(default='type', max_length=100),
        ),
    ]
