# Generated by Django 4.0.4 on 2022-05-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0020_alter_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=20),
        ),
    ]
