# Generated by Django 4.0.4 on 2022-05-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0021_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='category', max_length=100),
        ),
    ]
