# Generated by Django 4.0.4 on 2022-05-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0023_profile_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default='city', max_length=100),
        ),
    ]
