# Generated by Django 4.0.4 on 2022-08-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0026_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
