# Generated by Django 4.0.4 on 2022-08-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0027_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='udata',
            field=models.TextField(default='all', max_length=150),
        ),
    ]
