# Generated by Django 4.0.4 on 2022-08-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0028_post_date_modified_post_udata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='udata',
        ),
    ]
