# Generated by Django 4.0.4 on 2022-08-20 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0031_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testingapp.post')),
            ],
        ),
    ]
