# Generated by Django 4.0.4 on 2022-08-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0038_alter_photo_feed_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, to='testingapp.photo'),
        ),
    ]
