# Generated by Django 4.0.4 on 2022-08-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0041_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
