# Generated by Django 4.0.4 on 2022-08-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0043_alter_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(default='type', max_length=100),
        ),
    ]
