# Generated by Django 4.0.4 on 2022-09-24 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0051_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked', to='testingapp.profile'),
        ),
    ]
