# Generated by Django 4.0.4 on 2022-09-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0054_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
