# Generated by Django 4.0.4 on 2022-09-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0056_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislikes', to='testingapp.profile'),
        ),
    ]
