# Generated by Django 4.0.4 on 2022-10-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0058_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='Male', max_length=20),
        ),
    ]
