# Generated by Django 4.0.4 on 2022-11-30 10:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testingapp', '0060_setting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setting',
            new_name='testtheme',
        ),
    ]
