# Generated by Django 4.0.4 on 2022-11-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0065_alter_setting_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(default="{% static 'testingapp/new.css' %}", max_length=200),
        ),
    ]
