# Generated by Django 4.1.5 on 2024-06-11 13:03
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testingapp", "0066_alter_setting_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="CreditHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ("earned_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "credit_action",
                    models.CharField(
                        choices=[("earned", "Earned"), ("redeemed", "Redeemed"), ("new_recipe", "New recipe"), ("deleted", "Deleted")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="CreditSpentHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.IntegerField()),
                ("spent_timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=250)),
                ("message", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="RedeemedCredit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ("redeemed_timestamp", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="UserLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("location", models.CharField(blank=True, default="Location", max_length=200, null=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("primary_color", models.CharField(blank=True, default="#DBCBBD", max_length=20, null=True)),
                ("secondary_color", models.CharField(blank=True, default="#F0ECE3", max_length=20, null=True)),
                ("tertiary_color", models.CharField(blank=True, default="#221e20", max_length=20, null=True)),
                ("active_link_color", models.CharField(blank=True, default="#9F8772", max_length=20, null=True)),
                ("hover_color", models.CharField(blank=True, default="#9C938B", max_length=20, null=True)),
                ("theme", models.CharField(blank=True, default="theme", max_length=100, null=True)),
                ("neutral_primary", models.CharField(blank=True, default="#DBCBBD", max_length=20, null=True)),
                ("neutral_secondary", models.CharField(blank=True, default="#D8D9DA", max_length=20, null=True)),
                ("use_colors_from_image", models.BooleanField(default=False)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="city",
        ),
        migrations.AddField(
            model_name="post",
            name="difficulty",
            field=models.CharField(default="difficulty", max_length=100),
        ),
        migrations.AddField(
            model_name="post",
            name="favourites",
            field=models.ManyToManyField(blank=True, default=None, related_name="favourite", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="profile",
            name="credits",
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name="profile",
            name="credits_spent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="earned_credits",
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name="profile",
            name="hit_count",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="hitcount.hitcount"),
        ),
        migrations.AddField(
            model_name="profile",
            name="redeemed_credits",
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name="profile",
            name="send_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(blank=True, choices=[("Male", "Male"), ("Female", "Female")], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_img",
            field=models.ImageField(default="avatar.jpg", upload_to="profile"),
        ),
        migrations.DeleteModel(
            name="Setting",
        ),
        migrations.AddField(
            model_name="favorite",
            name="blog",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="testingapp.post"),
        ),
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="creditspenthistory",
            name="recipename",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="testingapp.post"),
        ),
        migrations.AddField(
            model_name="creditspenthistory",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="bloghistory",
            name="blog_post",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="testingapp.post"),
        ),
        migrations.AddField(
            model_name="bloghistory",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="blog_histories", to=settings.AUTH_USER_MODEL),
        ),
    ]
