# Generated by Django 4.1.5 on 2024-07-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0071_rename_x_profile_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preference',
            field=models.CharField(blank=True, choices=[('dinner', 'Dinner'), ('lunch', 'Lunch'), ('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian')], max_length=100, null=True),
        ),
    ]
