# Generated by Django 4.1.5 on 2024-07-18 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0073_alter_profile_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preference',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast recipes'), ('Lunch', 'Lunch recipes'), ('Snacks', 'Snacks recipes'), ('Dinner', 'Dinner recipes'), ('Veg', 'Veg recipes'), ('Non-Veg', 'Non-Veg recipes')], max_length=100, null=True),
        ),
    ]
