# Generated by Django 4.1.5 on 2024-07-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0074_alter_profile_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preference',
            field=models.CharField(blank=True, choices=[('Breakfast recipes', 'Breakfast recipes'), ('Lunch recipes', 'Lunch recipes'), ('Snacks recipes', 'Snacks recipes'), ('Dinner recipes', 'Dinner recipes'), ('Veg recipes', 'Veg recipes'), ('Non-Veg recipes', 'Non-Veg recipes')], max_length=100, null=True),
        ),
    ]
