# Generated by Django 4.1.5 on 2024-07-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0075_alter_profile_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preference',
        ),
        migrations.AddField(
            model_name='profile',
            name='preference_category',
            field=models.CharField(blank=True, choices=[('Veg recipes', 'Veg recipes'), ('Non-Veg recipes', 'Non-Veg recipes')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference_cuisine',
            field=models.CharField(blank=True, choices=[('Indian cuisine', 'Indian cuisine'), ('American cuisine', 'American cuisine'), ('Italian cuisine', 'Italian cuisine')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preference_type',
            field=models.CharField(blank=True, choices=[('Breakfast recipes', 'Breakfast recipes'), ('Lunch recipes', 'Lunch recipes'), ('Snacks recipes', 'Snacks recipes'), ('Dinner recipes', 'Dinner recipes')], max_length=100, null=True),
        ),
    ]
