# Generated by Django 4.1.5 on 2024-07-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0076_remove_profile_preference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preference_type',
            field=models.CharField(blank=True, choices=[('Breakfast recipes', 'Breakfast recipes'), ('Lunch recipes', 'Lunch recipes'), ('Evening Snack recipes', 'Evening Snack recipes'), ('Dinner recipes', 'Dinner recipes')], max_length=100, null=True),
        ),
    ]
