# Generated by Django 4.1.5 on 2024-07-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0077_alter_profile_preference_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preference_category',
            field=models.CharField(blank=True, choices=[('Select', 'Select'), ('Veg recipes', 'Veg recipes'), ('Non-Veg recipes', 'Non-Veg recipes')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preference_cuisine',
            field=models.CharField(blank=True, choices=[('Select', 'Select'), ('Indian cuisine', 'Indian cuisine'), ('American cuisine', 'American cuisine'), ('Italian cuisine', 'Italian cuisine')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preference_type',
            field=models.CharField(blank=True, choices=[('Select', 'Select'), ('Breakfast recipes', 'Breakfast recipes'), ('Lunch recipes', 'Lunch recipes'), ('Evening Snack recipes', 'Evening Snack recipes'), ('Dinner recipes', 'Dinner recipes')], max_length=100, null=True),
        ),
    ]
