# Generated by Django 4.1.5 on 2024-07-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0078_alter_profile_preference_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preference_category',
            field=models.CharField(choices=[('Select', 'Select'), ('Veg recipes', 'Veg recipes'), ('Non-Veg recipes', 'Non-Veg recipes')], default='Select', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preference_cuisine',
            field=models.CharField(choices=[('Select', 'Select'), ('Indian cuisine', 'Indian cuisine'), ('American cuisine', 'American cuisine'), ('Italian cuisine', 'Italian cuisine')], default='Select', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='preference_type',
            field=models.CharField(choices=[('Select', 'Select'), ('Breakfast recipes', 'Breakfast recipes'), ('Lunch recipes', 'Lunch recipes'), ('Evening Snack recipes', 'Evening Snack recipes'), ('Dinner recipes', 'Dinner recipes')], default='Select', max_length=100),
        ),
    ]
