# Generated by Django 4.1.5 on 2024-09-29 20:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testingapp', '0080_post_recipes_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='recipes_ranking',
        ),
        migrations.CreateModel(
            name='searchedRecipesRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_count', models.IntegerField(default=0)),
                ('date_searched', models.DateTimeField(default=datetime.datetime.now)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_rankings', to='testingapp.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_search_rankings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('recipe', 'user')},
            },
        ),
    ]
