# Generated by Django 4.1.5 on 2024-11-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0082_remove_searchedrecipesranking_search_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='goals',
            field=models.IntegerField(default=0),
        ),
    ]
