# Generated by Django 4.1.5 on 2025-09-30 15:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0084_remove_profile_goals_yearlygoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=384),
        ),
        migrations.AlterField(
            model_name='yearlygoal',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
