# Generated by Django 4.1.5 on 2025-09-30 20:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0085_post_embedding_alter_yearlygoal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='embedding',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
