# Generated by Django 4.1.5 on 2025-09-30 23:17

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0090_enable_pgvector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, null=True),
        ),
    ]
