# Generated by Django 4.2.10 on 2026-02-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0088_alter_yearlygoal_year_usertasteprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timing',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
