# Generated by Django 4.2.10 on 2026-02-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingapp', '0087_alter_post_embedding'),
        ('testingapp', '0089_alter_post_timing'),
    ]

    operations = [
    ]
