# Generated by Django 4.2.10 on 2026-02-09 16:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testingapp", "0086_alter_post_embedding"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
    ]