"""
Django settings for test_project project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
import sys
import warnings
from pathlib import Path

import dj_database_url
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

sys.path.insert(0, os.path.join(BASE_DIR, "third_party"))

warnings.filterwarnings("ignore", category=DeprecationWarning)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# When debug is set to false we need to serve static files (css, images) for ruuning locally from
# a server (currently we are using AWS S3, for that we need id & secret key)

# DEBUG = os.environ.get("DEBUG", "False").lower() == "true"


# ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS").split(" ")

ALLOWED_HOSTS = ["*"]

APPEND_SLASH = True

# SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"
# CACHES = {"default": {"BACKEND": "django.core.cache.backends.locmem.LocMemCache"}}

# Using Redis Cache
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "SSL": True,
            "SSL_PARAMETERS": {
                "ssl_cert_reqs": "required",
                "ssl_version": "PROTOCOL_TLSv1_2",
            },
        },
    }
}


SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

SESSION_COOKIE_AGE = 86400

# Celery
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND")
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = os.environ.get("CELERY_TIMEZONE", "UTC")
CELERY_BROKER_USE_SSL = False
CELERY_REDIS_BACKEND_USE_SSL = False

INSTALLED_APPS = [
    "testingapp.apps.TestingappConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "hitcount",
    "rest_framework",
    "django.contrib.humanize",
    "wkhtmltopdf",
    "chartjs",
    "anymail",
    "import_export",
    "gtts",
    "storages",
    "notifications",
    "tinymce",
    "django.contrib.sites",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "testingapp.middleware.CheckPasswordMiddleware",
    "testingapp.middleware.ClearExistingUserFirstnameMiddleware",
    "testingapp.middleware.GuestMiddleware",
]

if DEBUG:
    INSTALLED_APPS.append("django_browser_reload")
    MIDDLEWARE.append("django_browser_reload.middleware.BrowserReloadMiddleware")

# X_FRAME_OPTIONS = 'SAMEORIGIN'

# Open weather api
OPENWEATHERMAP_API_KEY = os.environ.get("OPENWEATHERMAP_API_KEY")

SPOONACULAR_API_KEY = os.environ.get("SPOONACULAR_API_KEY")

CELERY_BEAT_SCHEDULE = {
    "refresh-user-tastes-at-night": {
        "task": "testingapp.tasks.home_tasks.refresh_all_user_tastes",
        "schedule": crontab(hour=2, minute=0),  # 2am daily
    },
    "refresh-weather-every-2-hours-for-active-users": {
        "task": "testingapp.tasks.refresh_recent_user_weather",
        "schedule": crontab(minute=0, hour="*/2"),  # every 2hrs
    },
    "update-trending-posts-hourly": {
        "task": "testingapp.tasks.trending_post_tasks.update_trending_posts",
        "schedule": crontab(minute=0),  # every hour
    },
    "fill-missing-embeddings": {
        "task": "testingapp.tasks.text_embeddings_tasks.generate_recipe_embeddings",
        "schedule": crontab(hour=3, minute=0),  # every night at 3am
    },
}

SPOONACULAR_API_KEY = os.environ.get("SPOONACULAR_API_KEY")

# Openai api
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")

NUTRITION_API_KEY = os.environ.get("NUTRITION_API_KEY")

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY")

CLOUDFLARE_ACCOUNT_ID = os.environ.get("CLOUDFLARE_ACCOUNT_ID")
CLOUDFLARE_API_TOKEN = os.environ.get("CLOUDFLARE_API_TOKEN")

# Mailgun api
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp-relay.brevo.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = '"Yummy Recipes" <yummyrecipes@django.com>'

ROOT_URLCONF = "test_project.urls"

TAILWIND_APP_NAME = "theme"

INTERNAL_IPS = [
    "127.0.0.1",
]

NPM_BIN_PATH = r"C:\Program Files\nodejs\npm.cmd"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "testingapp.context_processors.search_autocomplete_data",
                "testingapp.context_processors.message_notifications",
                "testingapp.context_processors.most_searched_recipes",
                "testingapp.context_processors.todays_date",
                "testingapp.context_processors.guest_user_context",
                "testingapp.context_processors.recipes",
            ],
            "libraries": {
                "noti_date_filter": "testingapp.templatetags.noti_date_filter",
                "read_time_pluralize": "testingapp.templatetags.read_time_pluralize",
                "dictionary_values": "testingapp.templatetags.dictionary_values",
            },
        },
    },
]

WSGI_APPLICATION = "test_project.wsgi.application"

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_JQUERY_URL = "https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"
CKEDITOR_IMAGE_BACKEND = "pillow"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

ENVIRONMENT = os.environ.get("ENVIRONMENT")

if "DATABASE_URL" in os.environ:
    # for neon db or render built in db
    # DATABASES = {"default": dj_database_url.parse(os.environ.get("DATABASE_URL"))}

    # just for supabase
    DATABASES = {"default": dj_database_url.config(default=os.environ.get("DATABASE_URL"), conn_max_age=600, ssl_require=True)}

else:
    # PosgreSQL
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": os.environ.get("LOCAL_DB_NAME"),
            "USER": os.environ.get("LOCAL_DB_USER"),
            "PASSWORD": os.environ.get("LOCAL_DB_PASSWORD"),
            "HOST": os.environ.get("LOCAL_DB_HOST"),
            "PORT": "",
        }
    }

# Using database for suggesting recipes based on weather
DB_HOST = os.environ.get("DB_HOST")
DB_PORT = os.environ.get("DB_PORT", "5432")
DB_NAME = os.environ.get("DB_NAME")
DB_USER = os.environ.get("DB_USER")
DB_PASSWORD = os.environ.get("DB_PASSWORD")
DB_SSLMODE = os.environ.get("DB_SSLMODE", "prefer")

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

LANGUAGES = [
    ("en", "English"),
    ("fr", "French"),
    ("es", "Spanish"),
    # Add more languages as needed
]

USE_I18N = True  # Enable internationalization

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True

USE_L10N = True

USE_TZ = False

IMPORT_EXPORT_USE_TRANSACTIONS = True

LOCALE_PATHS = [
    os.path.join(BASE_DIR, "locale"),
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"

if "DATABASE_URL" not in os.environ:
    MEDIA_URL = "/media/"


MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, 'static'),
# )

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "testingapp", "static")

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

STORAGES = {
    "default": {"BACKEND": "storages.backends.s3boto3.S3Boto3Storage"},
    "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
}

# Explicit S3 toggle (never rely on DATABASE_URL for storage)
if "DATABASE_URL" in os.environ:
    AWS_ACCESS_KEY_ID = os.environ.get("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.environ.get("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.environ.get("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = os.environ.get("AWS_S3_REGION_NAME", "us-east-2")

    if not AWS_STORAGE_BUCKET_NAME:
        raise ValueError("AWS_STORAGE_BUCKET_NAME not set in environment variables")

    AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": AWS_ACCESS_KEY_ID,
                "secret_key": AWS_SECRET_ACCESS_KEY,
                "bucket_name": AWS_STORAGE_BUCKET_NAME,
                "region_name": AWS_S3_REGION_NAME,
            },
        },
        "staticfiles": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {"bucket_name": AWS_STORAGE_BUCKET_NAME},
        },
    }

    STATIC_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/static/"
    MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/images/"

else:
    # Local development
    STATIC_URL = "/static/"
    MEDIA_URL = "/media/"
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")

    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }


TINYMCE_DEFAULT_CONFIG = {
    # 'height': 500,
    # 'width': 1000,
    "cleanup_on_startup": True,
    "custom_undo_redo_levels": 20,
    "selector": "textarea:not(#customClipboardModalText)",
    "plugins": """
            textcolor save link image media preview codesample contextmenu
            table code lists insertdatetime  nonbreaking
            contextmenu directionality searchreplace wordcount visualblocks
            visualchars code autolink lists  charmap print  hr
            anchor pagebreak
            """,
    "toolbar1": """
            fullscreen preview bold italic underline | fontselect,
            fontsizeselect  | forecolor backcolor | alignleft alignright |
            aligncenter alignjustify | indent outdent | bullist numlist table |
            | link image media | codesample |
            """,
    "toolbar2": """
            visualblocks visualchars |
            charmap hr pagebreak nonbreaking anchor |  code |
            """,
    "contextmenu": "formats | link image",
    "menubar": True,
    "statusbar": True,
}

SITE_ID = 1

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
    "testingapp.backends.EmailBackend",
)

SOCIALACCOUNT_PROVIDERS = {
    "google": {
        "SCOPE": [
            "profile",
            "email",
        ],
        "AUTH_PARAMS": {
            "access_type": "online",
        },
        "CLIENT_ID": os.environ.get("GOOGLE_CLIENT_ID"),
        "SECRET": os.environ.get("GOOGLE_SECRET_KEY"),
    }
}

LOGIN_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"

SOCIALACCOUNT_ADAPTER = "testingapp.adapters.SocialAccountAdapter"
